# Generated by Django 2.2.16 on 2022-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
