# Generated by Django 2.2.16 on 2022-10-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221009_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretotitle',
            old_name='title1',
            new_name='title',
        ),
    ]
