# Generated by Django 2.2.16 on 2022-10-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221006_2301'),
        ('reviews', '0002_auto_20221006_2135'),
    ]

    operations = [
    ]
