# Generated by Django 2.2.16 on 2022-10-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_merge_20221008_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='film', max_length=256, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='drama', max_length=256, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год создания произведения'),
        ),
    ]
