# Generated by Django 2.2.16 on 2022-10-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221009_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genretotitle',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genretotitle',
            name='title',
        ),
    ]
