# Generated by Django 2.2.16 on 2022-10-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221008_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretotitle',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genretotitle',
            old_name='title',
            new_name='title_id',
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
