# Generated by Django 2.2.16 on 2022-10-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20221008_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretotitle',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genretotitle',
            old_name='title_id',
            new_name='title',
        ),
    ]
