# Generated by Django 2.2.16 on 2022-10-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20221008_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretotitle',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genretotitle',
            old_name='title',
            new_name='title_id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
    ]
