# Generated by Django 2.2.16 on 2022-10-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20221008_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
